### ISSUE TITLE
handle missing Q-IDs and redirects

### ISSUE THREAD

**Issue by Silvan-WMDE** [wmde/data-quality#15]
checking Q6, which seems to be the first skipped Q-ID, we currently get this error:

```
QID;statements;violations;warnings;suggestions;violated_statements
Traceback (most recent call last):
  File "checkConstraints.py", line 87, in <module>
    statementCount = countStatements(q_id)
  File "checkConstraints.py", line 29, in countStatements
    return pages[firstPageId]['pageprops']['wb-claims']
KeyError: 'pageprops'
```
In order to be able to run random sample sets, we need a way to ignore errors for skipped Q-IDs

Similarly, Q404 results in an error when trying to count the number of statements.

**Comment by mariushoch** [comment]
Solved by #18 :)
